"use client";

import { Provider } from "react-redux";
import store from "@lib/redux/store";
import "./globals.css";
import { Ubuntu } from "@app/fonts.js";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Ubuntu.className} bg-theme-light-sky-blue grid place-items-center min-h-screen`}
      >
        {/* <body className={`${Ubuntu.variable}`}> */}
        <Provider store={store}>
          <div className="md:p-4 md:w-[940px] md:bg-white">
            <main className="bg-mobile-bg-image md:bg-desktop-bg-image bg-no-repeat bg-contain p-4 relative">
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
