"use client";

import { Provider } from "react-redux";
import store from "@lib/redux/store";
import "./globals.css";
import { Ubuntu } from "@app/fonts.js";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Ubuntu.className} bg-theme-light-sky-blue`}>
        {/* <body className={`${Ubuntu.variable}`}> */}
        <Provider store={store}>
          <div className="relative bg-mobile-bg-image bg-no-repeat bg-contain p-4">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
